# Generated by Django 4.1.5 on 2023-01-29 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Run",
            fields=[
                (
                    "run_id",
                    models.CharField(
                        default="ZZZZ",
                        editable=False,
                        max_length=255,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                    ),
                ),
                ("run_date_time", models.DateField(null=True)),
                ("project_id", models.PositiveIntegerField(default=1)),
                ("data_scientist_id", models.PositiveIntegerField(default=1)),
                ("mlr_dataset", models.CharField(default="NA", max_length=255)),
                ("feature_set", models.CharField(default="NA", max_length=255)),
                ("split", models.FloatField(default=0.0)),
                ("tuned", models.BooleanField(default=False)),
                ("setup", models.CharField(default="NA", max_length=1000)),
                ("best", models.CharField(default="NA", max_length=1000)),
                ("holdout_acc", models.FloatField(default=0.0)),
                ("metrics_dict", models.CharField(default="NA", max_length=1000)),
                ("accuracy", models.FloatField(default=0.0)),
                ("roc_auc", models.FloatField(default=0.0)),
                ("recall", models.FloatField(default=0.0)),
                ("precision", models.FloatField(default=0.0)),
                ("f1", models.FloatField(default=0.0)),
                ("kappa", models.FloatField(default=0.0)),
                ("mcc", models.FloatField(default=0.0)),
            ],
        ),
    ]
