# Generated by Django 4.1.5 on 2023-01-29 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Run",
            fields=[
                (
                    "run_id",
                    models.CharField(
                        default="ZZZZ",
                        editable=False,
                        max_length=255,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                    ),
                ),
                ("project_id", models.PositiveIntegerField(default=1)),
                ("data_scientist_id", models.PositiveIntegerField(default=1)),
                ("mlr_dataset", models.CharField(default="NA", max_length=255)),
                ("split", models.FloatField(default=0.0)),
            ],
        ),
    ]
