# Generated by Django 4.1.5 on 2023-02-01 04:08

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Run",
            fields=[
                (
                    "run_id",
                    models.CharField(
                        default=uuid.uuid4,
                        editable=False,
                        max_length=255,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                    ),
                ),
                ("run_name", models.CharField(default="RUN_NAME", max_length=100)),
                ("run_date", models.CharField(max_length=100, null=True)),
                ("project_id", models.PositiveIntegerField(default=1)),
                ("data_scientist_id", models.PositiveIntegerField(default=1)),
                (
                    "mlr_dataset",
                    models.FileField(blank=True, null=True, upload_to="data/"),
                ),
                ("feature_set", models.CharField(default="NA", max_length=255)),
                ("split", models.FloatField(default=0.0)),
                ("tuned", models.BooleanField(default=False)),
                ("setup", models.CharField(default="NA", max_length=1000)),
                ("best", models.CharField(default="NA", max_length=1000)),
                ("holdout_acc", models.FloatField(default=0.0)),
                ("metrics_dict", models.CharField(default="NA", max_length=1000)),
                ("accuracy", models.FloatField(default=0.0)),
                ("roc_auc", models.FloatField(default=0.0)),
                ("recall", models.FloatField(default=0.0)),
                ("precision", models.FloatField(default=0.0)),
                ("f1", models.FloatField(default=0.0)),
                ("kappa", models.FloatField(default=0.0)),
                ("mcc", models.FloatField(default=0.0)),
            ],
        ),
    ]
