# Generated by Django 4.1.5 on 2023-02-01 04:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("runs", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="run",
            name="run_date",
            field=models.CharField(default="2023-01-01", max_length=100, null=True),
        ),
    ]
