# Generated by Django 4.1.5 on 2023-01-29 19:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("runs", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="run",
            old_name="run_date_time",
            new_name="run_date",
        ),
    ]
