# Generated by Django 4.1.5 on 2023-02-01 04:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("runs", "0002_alter_run_run_date"),
    ]

    operations = [
        migrations.AlterField(
            model_name="run",
            name="run_date",
            field=models.CharField(
                default="2023-01-01 09:00", max_length=100, null=True
            ),
        ),
    ]
