# Generated by Django 4.1.5 on 2023-02-18 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="project",
            name="agree",
            field=models.BooleanField(default=False),
        ),
    ]
