# Generated by Django 4.1.5 on 2023-02-18 13:24

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0002_project_agree"),
    ]

    operations = [
        migrations.AddField(
            model_name="project",
            name="importance",
            field=models.CharField(
                choices=[("very", "VERY"), ("medium", "MEDIUM"), ("low", "LOW")],
                default="VERY",
                max_length=32,
            ),
        ),
        migrations.AlterField(
            model_name="project",
            name="description",
            field=models.TextField(
                null=True, validators=[django.core.validators.MinLengthValidator(6)]
            ),
        ),
    ]
