# Generated by Django 4.1.7 on 2023-02-25 21:01

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Test",
            fields=[
                (
                    "id",
                    models.CharField(
                        default=uuid.uuid4,
                        editable=False,
                        max_length=255,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                    ),
                ),
                ("run_id", models.CharField(max_length=255)),
                ("project_id", models.PositiveIntegerField(default=0)),
                ("accuracy", models.FloatField(default=0.0)),
            ],
        ),
        migrations.CreateModel(
            name="UploadedFile",
            fields=[
                (
                    "id",
                    models.CharField(
                        default=uuid.uuid4,
                        editable=False,
                        max_length=255,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                    ),
                ),
                (
                    "uploaded_name",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "uploaded_filename",
                    models.FileField(blank=True, null=True, upload_to="data/"),
                ),
                ("uploaded_date", models.DateTimeField(auto_now_add=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="Run",
            fields=[
                (
                    "run_id",
                    models.CharField(
                        default=uuid.uuid4,
                        editable=False,
                        max_length=255,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                    ),
                ),
                ("project_id", models.PositiveIntegerField(default=1)),
                ("data_scientist_id", models.PositiveIntegerField(default=1)),
                (
                    "mlr_dataset",
                    models.CharField(default="datased-used", max_length=255),
                ),
                (
                    "model_used",
                    models.CharField(default="model-parameters", max_length=1000),
                ),
                ("holdout_acc", models.FloatField(default=0.0)),
                (
                    "metrics_dict",
                    models.CharField(
                        default="{'example_field':'value}", max_length=1000
                    ),
                ),
                ("accuracy", models.FloatField(default=0.0)),
                ("roc_auc", models.FloatField(default=0.0)),
                ("recall", models.FloatField(default=0.0)),
                ("precision", models.FloatField(default=0.0)),
                ("f1", models.FloatField(default=0.0)),
                ("kappa", models.FloatField(default=0.0)),
                ("mcc", models.FloatField(default=0.0)),
                (
                    "uploaded_file_id",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="csvs.uploadedfile",
                    ),
                ),
            ],
        ),
    ]
