# Generated by Django 4.1.7 on 2023-02-25 18:00

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Run',
            fields=[
                ('run_id', models.CharField(default=uuid.uuid4, editable=False, max_length=255, primary_key=True, serialize=False, unique=True)),
                ('run_name', models.CharField(default='RUN_NAME', max_length=100)),
                ('run_date', models.CharField(default='2000-01-01 00:00', max_length=100, null=True)),
                ('uploaded_filename', models.FileField(blank=True, null=True, upload_to='data/')),
                ('project_id', models.PositiveIntegerField(default=1)),
                ('data_scientist_id', models.PositiveIntegerField(default=1)),
                ('mlr_dataset', models.CharField(default='datased-used', max_length=255)),
                ('feature_set', models.CharField(default='all-or-red', max_length=255)),
                ('split', models.FloatField(default=0.0)),
                ('tuned', models.BooleanField(default=False)),
                ('setup', models.CharField(default='setup-config', max_length=1000)),
                ('model_used', models.CharField(default='model-parameters', max_length=1000)),
                ('holdout_acc', models.FloatField(default=0.0)),
                ('metrics_dict', models.CharField(default="{'example_field':'value}", max_length=1000)),
                ('accuracy', models.FloatField(default=0.0)),
                ('roc_auc', models.FloatField(default=0.0)),
                ('recall', models.FloatField(default=0.0)),
                ('precision', models.FloatField(default=0.0)),
                ('f1', models.FloatField(default=0.0)),
                ('kappa', models.FloatField(default=0.0)),
                ('mcc', models.FloatField(default=0.0)),
            ],
        ),
        migrations.CreateModel(
            name='UploadedFile',
            fields=[
                ('id', models.CharField(default=uuid.uuid4, editable=False, max_length=255, primary_key=True, serialize=False, unique=True)),
                ('uploaded_name', models.CharField(blank=True, max_length=100, null=True)),
                ('uploaded_filename', models.FileField(blank=True, null=True, upload_to='data/')),
                ('uploaded_date', models.DateTimeField(auto_now_add=True, null=True)),
            ],
        ),
    ]
