# Generated by Django 4.1.7 on 2023-02-25 22:10

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("csvs", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="pycaretrun",
            name="data_scientist_id",
        ),
        migrations.RemoveField(
            model_name="pycaretrun",
            name="f1",
        ),
        migrations.RemoveField(
            model_name="pycaretrun",
            name="holdout_acc",
        ),
        migrations.RemoveField(
            model_name="pycaretrun",
            name="kappa",
        ),
        migrations.RemoveField(
            model_name="pycaretrun",
            name="mcc",
        ),
        migrations.RemoveField(
            model_name="pycaretrun",
            name="metrics_dict",
        ),
        migrations.RemoveField(
            model_name="pycaretrun",
            name="precision",
        ),
        migrations.RemoveField(
            model_name="pycaretrun",
            name="project_id",
        ),
        migrations.RemoveField(
            model_name="pycaretrun",
            name="recall",
        ),
        migrations.RemoveField(
            model_name="pycaretrun",
            name="roc_auc",
        ),
        migrations.RemoveField(
            model_name="pycaretrun",
            name="uploaded_file",
        ),
    ]
