# Generated by Django 4.1.7 on 2023-02-24 20:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('csvs', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='run',
            name='run_date',
            field=models.CharField(default='2000-01-01 00:00', max_length=100, null=True),
        ),
    ]
