# Generated by Django 4.1.7 on 2023-02-25 17:40

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('csvs', '0002_alter_run_run_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='UploadedFile',
            fields=[
                ('id', models.CharField(default=uuid.uuid4, editable=False, max_length=255, primary_key=True, serialize=False, unique=True)),
                ('uploaded_name', models.CharField(default='RUN_NAME', max_length=100)),
                ('uploaded_filename', models.FileField(blank=True, null=True, upload_to='data/')),
                ('uploaded_date', models.DateTimeField(auto_now_add=True, null=True)),
            ],
        ),
    ]
