# Generated by Django 4.1.7 on 2023-02-25 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('csvs', '0003_uploadedfile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uploadedfile',
            name='uploaded_name',
            field=models.CharField(max_length=100),
        ),
    ]
