# Generated by Django 4.1.7 on 2023-02-24 20:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('csvs', '0004_alter_run_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='run',
            old_name='run_id',
            new_name='run_number',
        ),
    ]
