# Generated by Django 4.1.7 on 2023-02-25 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('csvs', '0004_alter_uploadedfile_uploaded_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uploadedfile',
            name='uploaded_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
