# Generated by Django 4.1.7 on 2023-02-24 20:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('csvs', '0005_rename_run_id_run_run_number'),
    ]

    operations = [
        migrations.RenameField(
            model_name='run',
            old_name='run_number',
            new_name='run_id',
        ),
    ]
