# Generated by Django 4.1.7 on 2023-02-24 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('csvs', '0006_rename_run_number_run_run_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='run',
            name='id',
        ),
        migrations.AlterField(
            model_name='run',
            name='run_id',
            field=models.CharField(max_length=255, primary_key=True, serialize=False),
        ),
    ]
